const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
  IS_LOADING: "IS_LOADING",
  IS_VIDEO: "IS_VIDEO",
  SET_SONG_RECENT: "SET_SONG_RECENT",
  // Music
  PLAY: "PLAY",
  SEARCH: "SEARCH",
  SET_ALBUM: "SET_ALBUM",
  PLAY_LIST_ALBUM: "PLAY_LIST_ALBUM",
  SET_SIDE_RIGHT: "SET_SIDE_RIGHT",
  SET_SONGS_SEARCH: "SET_SONGS_SEARCH ",
  SET_SONGS_ZINGCHART: "SET_SONGS_ZINGCHART ",
  SET_SCROLL_ARTIST: "SET_SCROLL_ARTIST",
};

export default actionTypes;
