const path = {
  PUBLIC: "/",
  HOME: "",
  LOGIN: "login",
  ZING_CHART: "zing-chart",
  ZING_CHART_WEEK: "zing-chart-tuan/:title/:id",
  STAR: "*",
  ALBUM__TITLE_ID: "album/:title/:id",
  PLAYLIST__TITLE_ID: "playlist/:title/:id",
  SEARCH: "tim-kiem",
  SEARCH_PLAYLIST: "playlist",
  ALL_SEARCH: "tat-ca",
  SONG_SEARCH: "bai-hat",
  ARTISTS: "artist",
  VIDEO: "video",
  VIDEO_CLIP: "video-clip/:title/:id.html",
  HOME_SINGER: ":singer",
  ZING_GROUP: "hub",
  ZING_MUSIC_ON_TOP: "moi-phat-hanh",
  MUSIC_TOP_100: "top100",
  RELEASE_NEW: "new-release/song",
  MUSIC_NEW: "moi-phat-hanh",
};
export default path;
